export {
  analyzeSingleSubmission,
  analyzeAllClassSubmissions,
  createClassActivity,
  createTeacherClass,
  deleteNotification,
  fetchClassActivities,
  fetchClassStudents,
  fetchClassSubmissions,
  fetchDocumentPreview,
  fetchUserNotifications,
  fetchSubmissionDetail,
  fetchTeacherAnalytics,
  fetchTeacherClasses,
  fetchTeacherOverview,
  markNotificationRead,
  type ActivityNotification,
  type ActivityAttachment,
  type ActivityDetail,
  type ActivitySubmissionType,
  type ClassActivity,
  type DocumentPreviewType,
  type PreviewDocument,
  type SubmissionAnalysisResult,
  type SubmissionAnalysisDetails,
  type SubmissionHistoryEntry,
  type SuspiciousSentence,
  type ExplainabilitySignal,
  type ClassSubmission,
  type EnrolledStudent,
  type TeacherAnalytics,
  type TeacherAnalyticsTotals,
  type TeacherMonthlyTrend,
  type TeacherSuspiciousClass,
  type TeacherOverview,
  type TeacherOverviewActivity,
  type TeacherOverviewStudent,
  type TeacherClass,
} from "../../../services/classService";
